### ISSUE TITLE
Test Flight

### ISSUE THREAD

**Issue by guzman109** [Beaver-Notes/Beaver-pocket#15]
**Question or Assistance Request**

- [x] I have reviewed existing issues and discussions to find a solution to my question.
- [x] I have checked the documentation and relevant resources for answers.
- [x] This question is related to the project and within the scope of this repository.

**Description**
Is the testflight app still available? Would love to test it out.

**Environment (if applicable)**
- Operating System: iOS
- Operating System Version: 17.5.1
- Version of the project : [e.g., v1.0.0]

**Steps to Reproduce (if relevant)**

1. [Step 1]
2. [Step 2]
3. [Step 3]

**Expected Result**

**Other Information**

**GitHub User (if applicable)**

**Screenshots (if applicable)**

**Labels (if known)**
- [Label 1]
- [Label 2]

**Assignees (if known)**
@username

**Milestone (if known)**
[milestone name]

**Comment by Daniele-rolli** [comment]
It looks like the build has expired since it was last released in May. I’m currently working on a new version, but I’ve fallen a bit behind schedule, which is why TestFlight isn’t available at the moment. I apologize for any inconvenience this may have caused and will update you as soon as we’re ready to ship a new TestFlight build.

**Comment by Daniele-rolli** [comment]
We just released the first release candidate on TestFlight. It's been a while, but we want to deliver the best experience, even though the app isn't fully backed yet.
